spring:
  datasource:
    url: jdbc:mysql://localhost:3306/electronic_db?useSSL=false
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/migrations/init_database.sql
    enabled: true #false is not use liquibase when no have new design
logging:
  level:
    org:
      hibernate: ERROR

