
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/electronic_db
    username: root
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: none
  messages:
    basename: messageErrors
    fallback-to-system-locale: false
  web:
    locale: vi_VN
    locale-resolver: fixed
  mail:
    host: smtp.gmail.com
    port: 587
    username: ebonikshop@gmail.com
    password: aibzzxjrffupjjrf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            anable: true
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: false #false is not use liquibase when no have new design
  jackson:
    deserialization:
      fail-on-unknown-properties: true
logging:
  level:
    org:
      hibernate: ERROR
app:
  frontend:
    cros:
     - http://localhost:3000/ #domain of user frontend
     - http://localhost:3001/ #domain of admin frontend


